In [1]:
import pandas as pd
import numpy as np

In [2]:
A=pd.read_csv('csv_files/tableA.csv')
B=pd.read_csv('csv_files/tableB.csv')
A.fillna('',inplace=True)
B.fillna('',inplace=True)
test=pd.read_csv('csv_files/test.csv')
train=pd.read_csv('csv_files/train.csv')

In [3]:
A.head()

id                            Song_Name        Artist_Name  \
0   0                        Runaway Train                Cam   
1   1                             Track 14                Omi   
2   2                       Lips Are Movin     Meghan Trainor   
3   3  I Want a Hippopotamus for Christmas  A Great Big World   
4   4                               Credit     Meghan Trainor   

                    Album_Name  \
0  Welcome to Cam Country - EP   
1                       Me 4 U   
2                        Title   
3  I 'll Be Home For Christmas   
4             Title ( Deluxe )   

                                               Genre       Price  \
0  Country , Music , Contemporary Country , Honky...      $ 0.99   
1        Pop/Rock , Music , Pop , Dance , R&B / Soul  Album Only   
2   Pop , Music , Pop/Rock , Dance , Rock , Teen Pop      $ 1.29   
3                                    Holiday , Music      $ 1.29   
4   Pop , Music , Rock , Pop/Rock , Dance , Teen Pop      $ 1.29   

                                           CopyRight  Time   Released  
0                      2015 Sony Music Entertainment  3:01  31-Mar-15  
1  2015 Ultra Records , LLC under exclusive licen...  3:41             
2  2014 , 2015 Epic Records , a division of Sony ...  3:01   9-Jan-15  
3  Compilation ( P ) 2014 Epic Records , a divisi...  2:20  24-Nov-14  
4  2014 , 2015 Epic Records , a division of Sony ...  2:51   9-Jan-15

In [5]:
released_A=np.array(np.array(A['Released']))
unique_month_A=[]
for released in released_A:
    if released:
        split_released=released.split('-')
        if len(split_released)==3:
            if split_released[1] not in unique_month_A:
                unique_month_A.append(split_released[1])
        else:
            pass
#             print(released)
unique_month_A

['Mar',
 'Jan',
 'Nov',
 'Apr',
 'Feb',
 'Jul',
 'Oct',
 'Dec',
 'May',
 'Aug',
 'Jun',
 'Sep']

In [6]:
month_str_to_num_A={
    'Mar':3,'Jan':1,'Nov':11,'Apr':4,
    'Feb':2,'Jul':7,'Oct':10,'Dec':12,
    'May':5,'Aug':8,'Jun':6,'Sep':9
}

In [7]:
released_B=np.array(np.array(B['Released']))
unique_month_B=[]
for released in released_B:
    released=released.replace(',',' ')
    if released:
        split_released=released.split()
        if len(split_released)==3:
            if split_released[0] not in unique_month_B:
                unique_month_B.append(split_released[0])
        else:
            print(released)
unique_month_B

Wozzeck
Alte Frau


['September',
 'November',
 'July',
 'February',
 'December',
 'April',
 'October',
 'August',
 'March',
 'June',
 'January',
 'May']

In [8]:
month_str_to_num_B={
    'September':9,'November':11,'July':7,'February':2,
    'December':12,'April':4,'October':10,'August':8,
    'March':3,'June':6,'January':1,'May':5
}

In [9]:
def jac_qgm_3_qgm_3(seq1, seq2):
    seq1=seq1.lower()
    seq2=seq2.lower()
    qgm1 = []
    qgm2 = []
    seq1 = '##' + seq1 + '$$'
    seq2 = '##' + seq2 + '$$'
    for i in range(len(seq1) - 2):
        qgm1.append(seq1[i:i + 3])
    for i in range(len(seq2) - 2):
        qgm2.append(seq2[i:i + 3])
    qgm1 = set(qgm1)
    qgm2 = set(qgm2)
    return len(qgm1 & qgm2) / len(qgm1 | qgm2)

def price_delta(price_a,price_b):
    if price_a=='' or '$ ' not in price_a:
        price_a=0
    else:
        price_a=float(price_a[2:])
    if price_b=='' or '$ ' not in price_b:
        price_b=0
    else:
        price_b=float(price_b[2:])
    return abs(price_a-price_b)
    
import datetime
def released_delta(released_a,released_b):
    if released_a=='':
        released_a=datetime.date(2022,2,19)  # the date that i write this code
    else:
        split_released=released_a.split('-')
        if len(split_released)==3:
            year=2000+int(split_released[2])
            month=month_str_to_num_A[split_released[1]]
            day=int(split_released[0])
            released_a=datetime.date(year,month,day)
        else:
            released_a=datetime.date(int(released_a),1,1)
    
    if released_b=='':
        released_b=datetime.date(2022,2,19)
    else:
        released_b=released_b.replace(',',' ')
        split_released=released_b.split()
        if len(split_released)==3:
            year=int(split_released[2])
            month=month_str_to_num_B[split_released[0]]
            day=int(split_released[1])
            released_b=datetime.date(year,month,day)
        else:
            released_b=datetime.date(2022,2,19)
    
    return abs((released_a-released_b).days)

In [19]:
seq1="I'll Be Home For The Holiday"
seq2="I'll Think Of You When Raining"
jac_qgm_3_qgm_3(seq1,seq2)

0.1111111111111111

In [10]:
train_data=open('csv_files/train_data.csv','w')
train_data.write('_id,idA,idB,Song_Name_jac,Artist_Name_jac,Album_Name_jac,Genre_jac,Price_delta,CopyRight_jac,Released_delta,label\n')
train_data.close()

In [12]:
train_data=open('csv_files/train_data.csv','a+')
_id=0
for index, row in train.iterrows():
    ltable_id,rtable_id,label=row
#     print(ltable_id,rtable_id,label)
    Song_Name_A=A['Song_Name'][ltable_id]
    Artist_Name_A=A['Artist_Name'][ltable_id]
    Album_Name_A=A['Album_Name'][ltable_id]
    Genre_A=A['Genre'][ltable_id]
    Price_A=A['Price'][ltable_id]
    CopyRight_A=A['CopyRight'][ltable_id]
    Time_A=A['Time'][ltable_id]
    Released_A=A['Released'][ltable_id]
    
    Song_Name_B=B['Song_Name'][rtable_id]
    Artist_Name_B=B['Artist_Name'][rtable_id]
    Album_Name_B=B['Album_Name'][rtable_id]
    Genre_B=B['Genre'][rtable_id]
    Price_B=B['Price'][rtable_id]
    CopyRight_B=B['CopyRight'][rtable_id]
    Time_B=B['Time'][rtable_id]
    Released_B=B['Released'][rtable_id]
    
    Song_Name_jac=jac_qgm_3_qgm_3(Song_Name_A,Song_Name_B)
    if label==1:
        print(Song_Name_A,'~~~',Song_Name_B,Song_Name_jac)
    Artist_Name_jac=jac_qgm_3_qgm_3(Artist_Name_A,Artist_Name_B)
    Album_Name_jac=jac_qgm_3_qgm_3(Album_Name_A,Album_Name_B)
    Genre_jac=jac_qgm_3_qgm_3(Genre_A,Genre_B)
    Price_delta=price_delta(Price_A,Price_B)
    CopyRight_jac=jac_qgm_3_qgm_3(CopyRight_A,CopyRight_B)
    Released_delta=released_delta(Released_A,Released_B)
    
    train_data.write('{},{},{},{},{},{},{},{},{},{},{}\n'.format(_id,ltable_id,rtable_id,Song_Name_jac,Artist_Name_jac,Album_Name_jac,Genre_jac,Price_delta,CopyRight_jac,Released_delta,label))
    
    _id+=1
    
train_data.close()

Silver and Gold ~~~ Silver And Gold 1.0
Halcyon ~~~ Halcyon 1.0
True Colors ( feat . Nicki Minaj ) ~~~ True Colors ( feat . Nicki Minaj ) [ Explicit ] 0.6666666666666666
Turn Around ( 5,4,3,2,1 ) [ DJ Bam Bam Radio Remix ] ~~~ Turn Around ( 5,4,3,2,1 ) 0.4716981132075472
Gone ~~~ Gone ( Album Version ( Edited ) ) [ Clean ] 0.08888888888888889
I Ai n't Livin ' Long Like This ~~~ I Ai n't Livin ' Long Like This 1.0
I Ca n't Go There ( Acoustic Version ) ~~~ I Ca n't Go There ( Acoustic Version ) 1.0
Who I Am With You ~~~ Who I Am With You 1.0
Doin ' My Thing ~~~ Doin ' My Thing 1.0
Whateva ( feat . Monty ) ~~~ Whateva ( feat . Monty ) [ Clean ] 0.631578947368421
Goner ~~~ Goner 1.0
Sunburn ( Bonus Track ) ~~~ Sunburn ( Deluxe Edition ) 0.2926829268292683
I Do n't Believe You ( Main Version ) ~~~ I Do n't Believe You 0.4878048780487805
We Run ~~~ We Run 1.0
Truce ~~~ Truce 1.0
That Lucky Old Sun ( Just Rolls Around Heaven All Day ) [ With Willie Nelson ] ~~~ That Lucky Old Sun ( Just Roll

In [126]:
test_data=open('csv_files/test_data.csv','w')
test_data.write('_id,idA,idB,Song_Name_jac,Artist_Name_jac,Album_Name_jac,Genre_jac,Price_delta,CopyRight_jac,Released_delta,label\n')
test_data.close()

In [127]:
test_data=open('csv_files/test_data.csv','a+')
_id=0
for index, row in test.iterrows():
    ltable_id,rtable_id,label=row
#     print(ltable_id,rtable_id,label)
    Song_Name_A=A['Song_Name'][ltable_id]
    Artist_Name_A=A['Artist_Name'][ltable_id]
    Album_Name_A=A['Album_Name'][ltable_id]
    Genre_A=A['Genre'][ltable_id]
    Price_A=A['Price'][ltable_id]
    CopyRight_A=A['CopyRight'][ltable_id]
    Time_A=A['Time'][ltable_id]
    Released_A=A['Released'][ltable_id]
    
    Song_Name_B=B['Song_Name'][rtable_id]
    Artist_Name_B=B['Artist_Name'][rtable_id]
    Album_Name_B=B['Album_Name'][rtable_id]
    Genre_B=B['Genre'][rtable_id]
    Price_B=B['Price'][rtable_id]
    CopyRight_B=B['CopyRight'][rtable_id]
    Time_B=B['Time'][rtable_id]
    Released_B=B['Released'][rtable_id]
    
    Song_Name_jac=jac_qgm_3_qgm_3(Song_Name_A,Song_Name_B)
    Artist_Name_jac=jac_qgm_3_qgm_3(Artist_Name_A,Artist_Name_B)
    Album_Name_jac=jac_qgm_3_qgm_3(Album_Name_A,Album_Name_B)
    Genre_jac=jac_qgm_3_qgm_3(Genre_A,Genre_B)
    Price_delta=price_delta(Price_A,Price_B)
    CopyRight_jac=jac_qgm_3_qgm_3(CopyRight_A,CopyRight_B)
    Released_delta=released_delta(Released_A,Released_B)
    
    test_data.write('{},{},{},{},{},{},{},{},{},{},{}\n'.format(_id,ltable_id,rtable_id,Song_Name_jac,Artist_Name_jac,Album_Name_jac,Genre_jac,Price_delta,CopyRight_jac,Released_delta,label))
    
    _id+=1
    
test_data.close()

In [128]:
train_data=pd.read_csv('csv_files/train_data.csv')
m_data=train_data[train_data.label==1]
u_data=train_data[train_data.label==0]
m_array=np.array(m_data)[:,3:-1]
u_array=np.array(u_data)[:,3:-1]

test_data=pd.read_csv('csv_files/test_data.csv')
test_array=np.array(test_data)[:,3:-1]
test_label=np.array(test_data)[:,-1]
test_label=test_label.astype(int)

In [133]:
len(m_array),sum(test_label),len(m_array)+sum(test_label)

(105, 27, 132)

In [134]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
x=np.concatenate((m_array,u_array),axis=0)
y=np.array([1]*len(m_array)+[0]*len(u_array))
clf=RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(x,y)
pred_label=clf.predict(test_array)
print('Accuracy', accuracy_score(test_label, pred_label))
print('Precision', precision_score(test_label, pred_label))
print('Recall', recall_score(test_label, pred_label))
print('f1_score', f1_score(test_label, pred_label))
confusion_matrix(test_label, pred_label)

Accuracy 0.8990825688073395
Precision 0.8076923076923077
Recall 0.7777777777777778
f1_score 0.7924528301886792


array([[77,  5],
       [ 6, 21]])

In [143]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
x=np.concatenate((m_array,u_array),axis=0)
y=np.array([1]*len(m_array)+[0]*len(u_array))
clf=RandomForestClassifier(max_depth=5, random_state=0)
clf.fit(x,y)
pred_label=clf.predict(test_array)
print('Accuracy', accuracy_score(test_label, pred_label))
print('Precision', precision_score(test_label, pred_label))
print('Recall', recall_score(test_label, pred_label))
print('f1_score', f1_score(test_label, pred_label))
confusion_matrix(test_label, pred_label)

Accuracy 0.9541284403669725
Precision 0.8928571428571429
Recall 0.9259259259259259
f1_score 0.9090909090909091


array([[79,  3],
       [ 2, 25]])

In [141]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
x=np.concatenate((m_array,u_array),axis=0)
y=np.array([1]*len(m_array)+[0]*len(u_array))
clf=RandomForestClassifier(max_depth=10, random_state=0)
clf.fit(x,y)
pred_label=clf.predict(test_array)
print('Accuracy', accuracy_score(test_label, pred_label))
print('Precision', precision_score(test_label, pred_label))
print('Recall', recall_score(test_label, pred_label))
print('f1_score', f1_score(test_label, pred_label))
confusion_matrix(test_label, pred_label)

Accuracy 0.963302752293578
Precision 0.896551724137931
Recall 0.9629629629629629
f1_score 0.9285714285714286


array([[79,  3],
       [ 1, 26]])

In [181]:
zero=79+3
one=27
b=4
c=5
a=zero-b
d=one-c
accuracy=(a+d)*1.0/(a+b+c+d)
precision=d*1.0/(b+d)
recall=d*1.0/(c+d)
f1=2*recall*precision/(recall+precision)
print('Accuracy',accuracy)
print('Precision',precision)
print('Recall',recall)
print('f1_score',f1)
print('array([[{},\t{}],'.format(a,b))
print('       [{},\t{}]])'.format(c,d))

Accuracy 0.9174311926605505
Precision 0.8461538461538461
Recall 0.8148148148148148
f1_score 0.830188679245283
array([[78,	4],
       [5,	22]])
